server:
  port: 8080
spring:
  application:
    name: SABSPLExamPortal
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/sabsepdb
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      format-sql: true
      ddl-auto: update
  security:
    filter:
      order: 10

logging:
  level:
    root: ${LOG_LEVEL}
  file:
    name: ${LOG_FILE_PATH}
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){green} %clr([%level]){magenta}  %c{1.} [%t] %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%level] %c{1.} [%t] %m%n"

app:
  # ,R-!belR=AwTp{a,q5yW#ujpnmw}Vc{~!y~W38UZ8KKt$jwKuo
  jwt-secret: LFItIWJlbFI9QXdUcHthLHE1eVcjdWpwbm13fVZje34heX5XMzhVWjhLS3QkandLdW8=
  jwt-expiration-milliseconds: 21600000 # 6 hours